# Generated by Django 3.2.6 on 2021-08-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NhaHangTiecCuoiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menudrink',
            name='image',
            field=models.ImageField(null=True, upload_to='img/drink'),
        ),
    ]
