# Generated by Django 3.2.6 on 2021-08-11 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NhaHangTiecCuoiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('event_type', models.IntegerField(choices=[('1', 'Wedding'), ('2', 'Conference')])),
            ],
            options={
                'db_table': 'service_type',
            },
        ),
        migrations.AddField(
            model_name='menudrink',
            name='image',
            field=models.ImageField(null=True, upload_to='drink'),
        ),
        migrations.AddField(
            model_name='menufood',
            name='image',
            field=models.ImageField(null=True, upload_to='food'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to='service'),
        ),
        migrations.AddField(
            model_name='weddinglobby',
            name='image',
            field=models.ImageField(null=True, upload_to='lobby'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NhaHangTiecCuoiApp.servicetype'),
        ),
    ]
