# Generated by Django 3.2.6 on 2021-08-11 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NhaHangTiecCuoiApp', '0002_auto_20210811_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'food_type',
            },
        ),
        migrations.AddField(
            model_name='menufood',
            name='food_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NhaHangTiecCuoiApp.foodtype'),
        ),
    ]
