# Generated by Django 3.2.6 on 2021-08-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NhaHangTiecCuoiApp', '0002_alter_menudrink_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddinglobby',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
