# Generated by Django 3.2.6 on 2021-08-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NhaHangTiecCuoiApp', '0003_weddinglobby_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Wedding'), (2, 'Conference')]),
        ),
        migrations.AlterField(
            model_name='weddinglobbyprice',
            name='time',
            field=models.IntegerField(choices=[(1, 'Morning'), (2, 'Noon'), (3, 'Evening')]),
        ),
    ]
