# Generated by Django 3.2.6 on 2021-08-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NhaHangTiecCuoiApp', '0004_auto_20210817_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Wedding'), (2, 'Conference'), (3, 'Birthday')]),
        ),
    ]
