# Generated by Django 3.2.6 on 2021-08-18 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NhaHangTiecCuoiApp', '0005_alter_servicetype_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_pay', to='NhaHangTiecCuoiApp.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='wedding_lobby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_lobby', to='NhaHangTiecCuoiApp.weddinglobby'),
        ),
        migrations.AlterField(
            model_name='menufood',
            name='food_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_foods', to='NhaHangTiecCuoiApp.foodtype'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='NhaHangTiecCuoiApp.servicetype'),
        ),
        migrations.AlterField(
            model_name='weddinglobbyprice',
            name='wedding_lobby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wedding_lobby_prices', to='NhaHangTiecCuoiApp.weddinglobby'),
        ),
    ]
