# Generated by Django 3.2.6 on 2021-12-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NhaHangTiecCuoiApp', '0008_alter_feedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='session',
            field=models.IntegerField(null=True),
        ),
    ]
