# Generated by Django 3.2.6 on 2021-12-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NhaHangTiecCuoiApp', '0009_invoice_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='session',
            field=models.IntegerField(default=1),
        ),
    ]
